# Generated by Django 5.0 on 2025-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': 'Participante de Evento', 'verbose_name_plural': 'Participantes de Eventos'},
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
