# Generated by Django 5.0 on 2025-03-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_funcao_alter_eventparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Padrão (R$)'),
        ),
    ]
