# Generated by Django 5.0 on 2025-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_funcao_valor_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado'), ('pendente', 'Pendente de Confirmação'), ('orcamento', 'Orçamento'), ('pre_producao', 'Pré-produção'), ('pos_producao', 'Pós-produção'), ('arquivado', 'Arquivado')], default='agendado', max_length=20, verbose_name='Situação'),
        ),
    ]
