# Generated by Django 5.0 on 2025-03-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('cadastrado', 'Cadastrado'), ('prospectado', 'Prospectado'), ('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado'), ('pendente', 'Pendente de Confirmação'), ('orcamento', 'Orçamento'), ('pre_producao', 'Pré-produção'), ('pos_producao', 'Pós-produção'), ('arquivado', 'Arquivado')], default='cadastrado', max_length=20, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('cadastrado', 'Cadastrado'), ('prospectado', 'Prospectado'), ('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado'), ('pendente', 'Pendente de Confirmação'), ('orcamento', 'Orçamento'), ('pre_producao', 'Pré-produção'), ('pos_producao', 'Pós-produção'), ('arquivado', 'Arquivado')], max_length=20, null=True, verbose_name='Status Anterior')),
                ('new_status', models.CharField(choices=[('cadastrado', 'Cadastrado'), ('prospectado', 'Prospectado'), ('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado'), ('pendente', 'Pendente de Confirmação'), ('orcamento', 'Orçamento'), ('pre_producao', 'Pré-produção'), ('pos_producao', 'Pós-produção'), ('arquivado', 'Arquivado')], max_length=20, verbose_name='Novo Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Mudança')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='events.event')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
