# Generated by Django 5.0 on 2025-03-24 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_status_eventstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Contratado (R$)'),
        ),
        migrations.CreateModel(
            name='EventCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('cost_type', models.CharField(choices=[('budget', 'Orçamento'), ('actual', 'Custo Real')], default='actual', max_length=10, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_costs', to='events.costcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='events.event')),
            ],
            options={
                'verbose_name': 'Custo de Evento',
                'verbose_name_plural': 'Custos de Eventos',
                'ordering': ['-date'],
            },
        ),
    ]
