# Generated by Django 5.0 on 2025-03-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_costcategory_alter_event_value_eventcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events_gallery/', verbose_name='Imagem')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
            ],
            options={
                'verbose_name': 'Foto da Galeria do Evento',
                'verbose_name_plural': 'Fotos da Galeria do Evento',
                'ordering': ['event__title', 'order', 'created_at'],
            },
        ),
    ]
