# Generated by Django 5.0 on 2025-03-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Condições de Pagamento')),
                ('validity_days', models.PositiveIntegerField(default=10, verbose_name='Validade da Proposta (dias)')),
                ('client_responsibilities', models.TextField(blank=True, verbose_name='Responsabilidades do Cliente')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Observações Adicionais')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_settings', to='events.event')),
            ],
            options={
                'verbose_name': 'Configuração de Orçamento',
                'verbose_name_plural': 'Configurações de Orçamento',
            },
        ),
        migrations.CreateModel(
            name='EventBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Horário Inicial')),
                ('end_time', models.TimeField(verbose_name='Horário Final')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
