# Generated by Django 5.0 on 2025-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_budgetsettings_eventbudgetitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('signature_name', models.CharField(help_text='Nome que aparecerá nas assinaturas de documentos', max_length=100, verbose_name='Nome para Assinatura')),
                ('signature_title', models.CharField(help_text='Cargo ou título que aparecerá abaixo do nome nas assinaturas', max_length=100, verbose_name='Cargo/Título')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
