# Generated by Django 5.0 on 2025-03-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='Condições de Pagamento')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Validade (dias)')),
                ('client_responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsabilidades do Cliente')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Padrão de Orçamento',
                'verbose_name_plural': 'Configurações Padrão de Orçamento',
            },
        ),
        migrations.AlterField(
            model_name='budgetsettings',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Adicionais'),
        ),
        migrations.AlterField(
            model_name='budgetsettings',
            name='client_responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidades do Cliente'),
        ),
        migrations.AlterField(
            model_name='budgetsettings',
            name='payment_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Condições de Pagamento'),
        ),
        migrations.AlterField(
            model_name='budgetsettings',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Validade (dias)'),
        ),
    ]
