# Generated by Django 5.0 on 2025-03-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_defaultbudgetsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultbudgetsettings',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='Dados Bancários'),
        ),
    ]
