# Generated by Django 5.0 on 2025-03-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_alter_occurrence_options_alter_occurrence_related_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
    ]
