# Generated by Django 5.0 on 2025-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('outro', 'Outro')], max_length=20),
        ),
    ]
