# Generated by Django 5.0 on 2025-03-20 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_altura_person_cor_cabelo_person_cor_olhos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorCabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cor de Cabelo',
                'verbose_name_plural': 'Cores de Cabelo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CorOlhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cor de Olhos',
                'verbose_name_plural': 'Cores de Olhos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CorPele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cor de Pele',
                'verbose_name_plural': 'Cores de Pele',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='cor_cabelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.corcabelo', verbose_name='Cor do cabelo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cor_olhos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.corolhos', verbose_name='Cor dos olhos'),
        ),
        migrations.AddField(
            model_name='person',
            name='cor_pele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.corpele', verbose_name='Cor da pele'),
        ),
        migrations.AddField(
            model_name='person',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.genero', verbose_name='Gênero'),
        ),
    ]
