# Generated by Django 5.0 on 2025-03-20 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_corcabelo_corolhos_corpele_genero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='personcontact',
            options={'ordering': ['person__name', 'type'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='person',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='person',
            name='manequim',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Manequim'),
        ),
        migrations.AlterField(
            model_name='person',
            name='appearance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Aparência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='communication',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comunicação'),
        ),
        migrations.AlterField(
            model_name='person',
            name='efficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Eficiência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people_photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='person',
            name='proactivity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Proatividade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='punctuality',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Pontualidade'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='label',
            field=models.CharField(blank=True, help_text='Ex: Pessoal, Trabalho, etc.', max_length=100, null=True, verbose_name='Rótulo'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
    ]
