# Generated by Django 5.0 on 2025-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_person_options_alter_personcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
    ]
