# Generated by Django 5.0 on 2025-03-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria Profissional',
                'verbose_name_plural': 'Categorias Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='professional_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.professionalcategory', verbose_name='Categoria Profissional'),
        ),
    ]
