# Generated by Django 5.0 on 2025-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_professionalcategory_person_professional_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='professional_category',
        ),
        migrations.AddField(
            model_name='person',
            name='professional_categories',
            field=models.ManyToManyField(blank=True, to='people.professionalcategory', verbose_name='Categorias Profissionais'),
        ),
    ]
