# Generated by Django 5.0 on 2025-03-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_remove_person_professional_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('bloqueado', 'Bloqueado'), ('em_avaliacao', 'Em Avaliação'), ('licenca_temporaria', 'Licença Temporária'), ('arquivado', 'Arquivado')], default='pendente', max_length=20, verbose_name='Situação'),
        ),
    ]
