# Generated by Django 5.0 on 2025-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_persongallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='origem_cadastro',
            field=models.CharField(choices=[('interno', 'Interno (Escritório)'), ('externo', 'Externo (Site)')], default='interno', max_length=20, verbose_name='Origem do Cadastro'),
        ),
    ]
