# Generated by Django 5.0 on 2025-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_castingcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingcatalog',
            name='origem_cadastro',
            field=models.TextField(blank=True, null=True, verbose_name='Origem do Cadastro'),
        ),
    ]
