# Generated by Django 5.0 on 2025-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_castingcatalog_origem_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingcatalog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
