# Generated by Django 5.0 on 2025-04-06 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_personcomment_personview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='people.castingcatalog')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='people.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seleção de Pessoa',
                'verbose_name_plural': 'Seleções de Pessoas',
                'unique_together': {('person', 'catalog', 'session_key')},
            },
        ),
    ]
